name: lizshannon
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46629
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1ebdbd'
    - '#008080'
    - '#00ffff'
    - '#000000'
    - '#00d5d5'
  brandStrength: 0.6207718013320118
  lightness: 0.17388603882864118
  saturation: 0.3708824827335775
  rhythmicContrast: 0.1410375137347728
purpose: []
