name: lizshannon
favicon: null
layout_spectrum: 0.6314325502607971
typography_spectrum: 0.22205000673420727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6207718013320118
  lightness: 0.17388603882864118
  saturation: 0.3708824827335775
  rhythmicContrast: 0.1410375137347728
purpose: []
